import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#adc6ff',
        'on-surface': '#dae2fd',
        'on-primary-fixed-variant': '#004e5c',
        'on-tertiary-container': '#5a009b',
        'surface-dim': '#0b1326',
        outline: '#869397',
        'tertiary-fixed': '#f0dbff',
        'primary-container': '#06b6d4',
        'inverse-surface': '#dae2fd',
        'secondary-fixed': '#d8e2ff',
        'inverse-primary': '#00687a',
        'surface-tint': '#4cd7f6',
        primary: '#4cd7f6',
        'surface-container-highest': '#2d3449',
        'surface-container-low': '#131b2e',
        'surface-variant': '#2d3449',
        tertiary: '#ddb7ff',
        'on-surface-variant': '#bcc9cd',
        'error-container': '#93000a',
        'tertiary-container': '#c78dff',
        'surface-container-high': '#222a3d',
        'on-tertiary-fixed-variant': '#6900b3',
        'surface-container-lowest': '#060e20',
        'on-secondary-container': '#e6ecff',
        'on-error': '#690005',
        surface: '#0b1326',
        'secondary-container': '#0566d9',
        'on-primary-container': '#00424f',
        'surface-bright': '#31394d',
        'secondary-fixed-dim': '#adc6ff',
        error: '#ffb4ab',
        'on-primary': '#003640',
        'primary-fixed': '#acedff',
        'on-primary-fixed': '#001f26',
        'on-secondary': '#002e6a',
        'on-secondary-fixed': '#001a42',
        'inverse-on-surface': '#283044',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#490080',
        'on-secondary-fixed-variant': '#004395',
        'surface-container': '#171f33',
        'primary-fixed-dim': '#4cd7f6',
        'on-background': '#dae2fd',
        'tertiary-fixed-dim': '#ddb7ff',
        'on-tertiary-fixed': '#2c0051',
        background: '#0b1326',
        'outline-variant': '#3d494c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        unit: '4px',
      },
      fontFamily: {
        'label-md': ['var(--font-mono)', 'monospace'],
        'label-sm': ['var(--font-mono)', 'monospace'],
        'headline-lg': ['var(--font-sora)', 'sans-serif'],
        'headline-md': ['var(--font-sora)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'display-lg': ['var(--font-sora)', 'sans-serif'],
        'display-lg-mobile': ['var(--font-sora)', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.5', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.5', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        shimmer: 'shimmer 15s linear infinite',
        'pulse-glow': 'pulse-glow 3s infinite',
        blink: 'blink 1s step-end infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-15px) rotate(2deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% -200%' },
          '100%': { backgroundPosition: '200% 200%' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 15px rgba(6, 182, 212, 0.3)' },
          '50%': { boxShadow: '0 0 30px rgba(6, 182, 212, 0.6)' },
        },
        blink: {
          '50%': { opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
